// SPDX-License-Identifier: CC0-1.0
// Public-domain example code (CC0) - see LICENSE.
#ifndef BSCHUB_EXAMPLE_CERT_TOOL_H
#define BSCHUB_EXAMPLE_CERT_TOOL_H

// cert_tool.h
// =============================================================================
// Lab certificate generation for this example's BACnet/SC hub, built into the
// executable itself (OpenSSL is already linked for the SC transport), so a
// user needs no separate `openssl` binary:
//
//   --generate-certs [n]      A fresh set in --sc-cert-dir: a lab issuer (CA),
//                             this hub's own operational certificate, private
//                             key and certificate signing request, and n
//                             labeled client certificate sets (default 3) for
//                             the devices that connect to the hub.
//   --add-client-certs [n]    n MORE client sets (default 1), signed by the
//                             issuer ALREADY in --sc-cert-dir, so every
//                             existing peer and the running hub keep trusting
//                             them. Numbering continues after the highest
//                             existing label.
//   --cert-label <prefix>     Label prefix for client sets. Default "client",
//                             giving client-01, client-02, ...
//
// FILE NAMES follow the BACnet Network Port properties that carry them
// (ANSI/ASHRAE 135 cl. 12.56: Operational_Certificate_File,
// Issuer_Certificate_Files, Certificate_Signing_Request_File). Everything is
// PEM:
//
//   <sc-cert-dir>/                        this hub
//       operational-certificate.pem       Operational_Certificate_File (File 1)
//       private-key.pem                   the operational certificate's key
//                                         (never served by any File object)
//       certificate-signing-request.pem   Certificate_Signing_Request_File (File 2)
//       issuer-certificate.pem            Issuer_Certificate_Files (Files 3, 4)
//       issuer-private-key.pem            the issuer's key - only used to sign
//                                         more clients; keep it private
//       certificates.txt                  label, files, serial, expiry and
//                                         SHA-256 fingerprint of each certificate
//   <sc-cert-dir>/clients/<label>/        one folder per connecting device -
//       operational-certificate.pem       hand the whole folder to that device
//       private-key.pem
//       issuer-certificate.pem            (a copy of the hub's issuer)
//       bacnetsc.config                   BACnet/SC connection settings (hub
//                                         URI + the three files above) that
//                                         the Chipkin BACnet Explorer imports
//       readme.txt
//
// Every certificate is LABELED twice: by its folder (clients/client-01/) and
// in its subject Common Name ("Chipkin Example B-SCHUB client-01"), so a
// peer's certificate can be traced back to its files from the hub's logs or a
// TLS capture.
//
// Key and certificate profile:
// ECDSA P-256, SHA-256, issuer valid 10 years, leaves 825 days; the hub gets
// EKU serverAuth+clientAuth with SAN localhost/127.0.0.1/<hostname>, clients
// get EKU clientAuth. The hub also still reads the older file names (hub.crt,
// hub.key, hub.csr, ca.crt, ca.key) from earlier releases - see
// ResolveCertFile().
//
// LAB TESTING ONLY. A real deployment uses its own PKI - see README.md
// "BACnet/SC support".
// =============================================================================

#include <string>

namespace CertTool {

static const unsigned DEFAULT_GENERATE_CLIENT_COUNT = 3;
static const unsigned DEFAULT_ADD_CLIENT_COUNT = 1;
static const char* const DEFAULT_CLIENT_LABEL = "client";

// File names, relative to --sc-cert-dir (or to a client's folder).
static const char* const OPERATIONAL_CERTIFICATE_FILE = "operational-certificate.pem";
static const char* const PRIVATE_KEY_FILE = "private-key.pem";
static const char* const CERTIFICATE_SIGNING_REQUEST_FILE = "certificate-signing-request.pem";
static const char* const ISSUER_CERTIFICATE_FILE = "issuer-certificate.pem";
static const char* const ISSUER_PRIVATE_KEY_FILE = "issuer-private-key.pem";
// Issuer Certificate Slot 2's own file. Absent until a client writes a second
// issuer over BACnet (clause 19.8.3); until then File 4 serves slot 1's file.
static const char* const ISSUER_CERTIFICATE_2_FILE = "issuer-certificate-2.pem";
// Generated by the hub at startup and after a certificate change: every issuer
// certificate from both slots, which is what TLS trusts peers against.
static const char* const TRUSTED_ISSUERS_FILE = "trusted-issuers.pem";
static const char* const CLIENTS_DIR = "clients";
static const char* const BACNETSC_CONFIG_FILE = "bacnetsc.config";

// The older file names used by earlier releases (still read).
static const char* const LEGACY_OPERATIONAL_CERTIFICATE_FILE = "hub.crt";
static const char* const LEGACY_PRIVATE_KEY_FILE = "hub.key";
static const char* const LEGACY_CERTIFICATE_SIGNING_REQUEST_FILE = "hub.csr";
static const char* const LEGACY_ISSUER_CERTIFICATE_FILE = "ca.crt";
static const char* const LEGACY_ISSUER_PRIVATE_KEY_FILE = "ca.key";

// Picks which name to use in certDir: `name` if that file exists or `legacyName`
// doesn't, otherwise `legacyName`. So a directory from --generate-certs uses
// the BACnet names, and one from an earlier release keeps working unchanged. Returns a name relative to certDir.
std::string ResolveCertFile(const std::string& certDir, const char* name, const char* legacyName);

// Creates the hub's files and `clientCount` labeled client folders in certDir
// (created if missing). Refuses to touch an existing issuer or hub
// certificate/key (either naming) unless `force` is true, because replacing
// the issuer invalidates every certificate already handed out; with `force`
// the old set, the clients/ folder and certificates.txt are deleted first.
// Prints what it wrote. Returns true on success.
// `hubUri` (e.g. "wss://192.168.1.10:47819/") is the primary hub URI written
// into each client's bacnetsc.config.
bool GenerateCertificateSet(const std::string& certDir, unsigned clientCount,
                            const std::string& clientLabel, const std::string& hubUri, bool force);

// Signs `clientCount` more labeled client sets with the issuer already in
// certDir (either naming). Numbering continues after the highest
// clients/<clientLabel>-NN folder already present. Never overwrites a file.
// Returns true on success.
bool AddClientCertificates(const std::string& certDir, unsigned clientCount,
                           const std::string& clientLabel, const std::string& hubUri);

}  // namespace CertTool

#endif  // BSCHUB_EXAMPLE_CERT_TOOL_H
